#!/bin/sh
# postinst script for caja-wipe
#
# see: dh_installdeb(1)

set -e

unud=/var/lib/update-notifier/user.d

if [ -d $unud ]; then
	cp /usr/share/caja-compare/caja-wipe-notification \
		/var/lib/update-notifier/user.d/
	touch /var/lib/update-notifier/dpkg-run-stamp
fi

#DEBHELPER#
