#!/bin/sh
# prerm script for caja-wipe
#
# see: dh_installdeb(1)

set -e

case "$1" in
    remove|upgrade|deconfigure)
        rm -f /var/lib/update-notifier/user.d/caja-wipe-notification
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
